ALTER TABLE `providers` ALTER COLUMN `created_at` DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `providers` ALTER COLUMN `updated_at` DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `sms` ALTER COLUMN `created_at` DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `sms` ALTER COLUMN `updated_at` DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `templates` ALTER COLUMN `created_at` DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `templates` ALTER COLUMN `updated_at` DEFAULT CURRENT_TIMESTAMP;